version: '3.9'

services:
  db:
    container_name: crud-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - django_net

  web:
    container_name: crud-web
    build: .
    command: >
      sh -c "poetry run python manage.py makemigrations &&
            poetry run python manage.py migrate &&
            poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - django_net

volumes:
  postgres_data:

networks:
  django_net:
    driver: 'bridge'
