# Generated by Django 5.1 on 2024-08-27 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('alpha_vantage', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
